spring:
  application:
    name: Employee Data Management System
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:}
    url: ${DATASOURCE_URL:jdbc:h2:mem:employee-data-management}
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/octet-stream
    min-response-size: 1024
